//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.Flight_Company = new HashSet<Flight_Company>();
        }
    
        public int CompanyId { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
    
        public virtual ICollection<Flight_Company> Flight_Company { get; set; }
    }
}
