//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        public Flight()
        {
            this.Flight_Company = new HashSet<Flight_Company>();
            this.Flight_Plane = new HashSet<Flight_Plane>();
            this.Flight_Ticket = new HashSet<Flight_Ticket>();
        }
    
        public int FlightId { get; set; }
        public string Info { get; set; }
    
        public virtual ICollection<Flight_Company> Flight_Company { get; set; }
        public virtual ICollection<Flight_Plane> Flight_Plane { get; set; }
        public virtual ICollection<Flight_Ticket> Flight_Ticket { get; set; }
    }
}
