//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AirportEntities : DbContext
    {
        public AirportEntities()
            : base("name=AirportEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Company> Company { get; set; }
        public DbSet<Flight> Flight { get; set; }
        public DbSet<Flight_Company> Flight_Company { get; set; }
        public DbSet<Flight_Plane> Flight_Plane { get; set; }
        public DbSet<Flight_Ticket> Flight_Ticket { get; set; }
        public DbSet<Plane> Plane { get; set; }
        public DbSet<Ticket> Ticket { get; set; }
    }
}
